import re

path = 'Assets/Scripts/Core/Testing/FullDateContent.cs'
with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = [
    # Specific clauses & idioms
    ("he had been holding back", "you had been holding back"),
    ("wishes he had shown", "wishes you had shown"),
    ("tells her he is still", "tells her you are still"),
    ("so he does not", "so you do not"),
    ("that he did not", "that you did not"),
    ("waits for him to", "waits for you to"),
    ("does not press him", "does not press you"),
    ("what he actually feels", "what you actually feel"),
    ("how worried he is", "how worried you are"),
    ("make him feel", "make you feel"),
    ("shows he hit", "shows you hit"),
    ("why he looks so", "why you look so"),
    ("wonder if he is not", "wonder if you are not"),
    ("what he is covering", "what you are covering"),
    ("whether he is flirting", "whether you are flirting"),
    ("whether he is joking", "whether you are joking"),
    ("tell he is more embarrassed", "tell you are more embarrassed"),
    ("sensing he is", "sensing you are"),
    ("how seriously he took", "how seriously you took"),
    ("what he wants to know", "what you want to know"),
    ("things he built", "things you built"),
    ("as he fills", "as you fill"),
    ("how relaxed he is", "how relaxed you are"),
    ("pleased he looks", "pleased you look"),
    ("pleased he played", "pleased you played"),
    ("how interested he sounds", "how interested you sound"),
    ("pressure he feels", "pressure you feel"),
    ("not derailing him", "not derailing you"),
    ("pressure he just put on himself", "pressure you just put on yourself"),
    ("words failing him as he smiles nervously", "words failing you as you smile nervously"),
    ("avoids making him guess", "avoids making you guess"),
    ("whether she likes him", "whether she likes you"),
    ("matching his playful tone", "matching your playful tone"),
    ("matching his honesty", "matching your honesty"),
    ("his easy reaction", "your easy reaction"),
    ("gives his hand an reassuring tap", "gives your hand a reassuring tap"),
    ("gives his hand a reassuring tap", "gives your hand a reassuring tap"),
    ("when he looks back", "when you look back"),
    ("unsettled him", "unsettled you"),
    ("though his concern", "though your concern"),
    ("how quickly he panicked", "how quickly you panicked"),
    ("back off him", "back off you"),
    ("looking down at his plate", "looking down at your plate"),
    ("looking down at his hands", "looking down at your hands"),
    ("looking down at his drink", "looking down at your drink"),
    ("happy he played along", "happy you played along"),
    ("his own thoughts", "your own thoughts"),
    ("without making him keep proving it", "without making you keep proving it"),
    ("where his mind went", "where your mind went"),
    ("his alarm", "your alarm"),
    ("glimpse of his nerves", "glimpse of your nerves"),
    ("helping him settle", "helping you settle"),
    ("inviting him to keep talking", "inviting you to keep talking"),
    ("opening to talk about himself", "opening to talk about yourself"),
    ("doesn't meet his eyes", "doesn't meet your eyes"),
    ("not looking at him", "not looking at you"),
    ("looking at him for a second", "looking at you for a second"),
    ("looking at him", "looking at you"),
    ("put on himself", "put on yourself"),
    ("protecting himself", "protecting yourself"),
    ("about himself", "about yourself"),
    ("to himself", "to yourself"),
    ("at himself", "at yourself"),
    ("by himself", "by yourself"),
    ("catches himself", "catch yourself"),
    ("himself", "yourself"),
    ("*He catches himself.*", "*You catch yourself.*"),
    ("*He catches himself", "*You catch yourself"),
    ("*He catch yourself.*", "*You catch yourself.*"),
    ("*He gives her an easy smile", "*You give her an easy smile"),
    ("*He waits, then awkwardly takes a drink when the silence stretches.*", "*You wait, then awkwardly take a drink when the silence stretches.*"),
    ("*He notices the smile and lets her have the moment.*", "*You notice the smile and let her have the moment.*"),
    ("*He notices the yawn and freezes up completely, unsure whether to acknowledge it.*", "*You notice the yawn and freeze up completely, unsure whether to acknowledge it.*"),
    ("responsible for his nerves.", "responsible for your nerves."),
    ("*He notices the time check and goes quiet.*", "*You notice the time check and go quiet.*"),
    ("*He stares at her blankly, paralyzed by anticipation of what she might ask.*", "*You stare at her blankly, paralyzed by anticipation of what she might ask.*"),

    # Actions in answers
    ("*He smiles,", "*You smile,"),
    ("*He smiles.*", "*You smile.*"),
    ("*He smiles *", "*You smile *"),
    ("*He smiles", "*You smile"),
    ("*He laughs,", "*You laugh,"),
    ("*He laughs.*", "*You laugh.*"),
    ("*He laughs *", "*You laugh *"),
    ("*He laughs", "*You laugh"),
    ("*He grins,", "*You grin,"),
    ("*He grins.*", "*You grin.*"),
    ("*He grins *", "*You grin *"),
    ("*He grins", "*You grin"),
    ("*He blinks,", "*You blink,"),
    ("*He blinks", "*You blink"),
    ("*He pauses.*", "*You pause.*"),
    ("*He pauses", "*You pause"),
    ("*He takes a sip", "*You take a sip"),
    ("*He takes a breath,", "*You take a breath,"),
    ("*He leans back,", "*You lean back,"),
    ("*He catches her eye", "*You catch her eye"),
    ("*He catches his breath,", "*You catch your breath,"),
    ("*He settles back,", "*You settle back,"),
    ("*He settles into", "*You settle into"),
    ("*He watches her", "*You watch her"),
    ("*He freezes completely,", "*You freeze completely,"),
    ("*He freezes with a sheepish grin,", "*You freeze with a sheepish grin,"),
    ("*He freezes,", "*You freeze,"),
    ("*He hesitates,", "*You hesitate,"),
    ("*He breaks into", "*You break into"),
    ("*He starts to speak,", "*You start to speak,"),
    ("*He rubs his forehead,", "*You rub your forehead,"),
    ("*He rubs", "*You rub"),
    ("*He shakes his head", "*You shake your head"),
    ("*He shakes", "*You shake"),
    ("*He shrugs,", "*You shrug,"),
    ("*He shrugs", "*You shrug"),
    ("*He swallows,", "*You swallow,"),
    ("*He swallows", "*You swallow"),
    ("*He flushes,", "*You flush,"),
    ("*He tries to", "*You try to"),
    ("*He notices,", "*You notice,"),
    ("*He waits until", "*You wait until"),
    ("*He follows her", "*You follow her"),
    ("*He eats too,", "*You eat too,"),
    ("*He exhales,", "*You exhale,"),
    ("*He relaxes into", "*You relax into"),
    ("*He relaxes,", "*You relax,"),
    ("*He almost starts", "*You almost start"),
    ("*He sits rigid,", "*You sit rigid,"),
    ("*He sits frozen", "*You sit frozen"),
    ("*He looks at her", "*You look at her"),
    ("*He looks down", "*You look down"),
    ("*His eyes widen,", "*Your eyes widen,"),
    ("*He stays quiet,", "*You stay quiet,"),
    ("*He clears his throat", "*You clear your throat"),
    ("*He immediately fidgets with his glass.*", "*You immediately fidget with your glass.*"),
    ("*He immediately fidgets", "*You immediately fidget"),
    ("*He straightens too quickly,", "*You straighten too quickly,"),
    ("*He stares at the napkin,", "*You stare at the napkin,"),
    ("*He opens his mouth,", "*You open your mouth,"),
    ("*He gives her an approving nod.*", "*You give her an approving nod.*"),
    ("*He gives her a small, knowing smile.*", "*You give her a small, knowing smile.*"),
    ("*He asks it casually,", "*You ask it casually,"),
    ("*He reaches out reflexively", "*You reach out reflexively"),
    ("*He holds her gaze", "*You hold her gaze"),
    ("*He meets her eyes", "*You meet her eyes"),
    ("*He loses the sentence.*", "*You lose the sentence.*"),

    # Possessions
    ("his neck", "your neck"),
    ("his drink", "your drink"),
    ("his glass", "your glass"),
    ("his food", "your food"),
    ("his chair", "your chair"),
    ("his eyes", "your eyes"),
    ("his gaze", "your gaze"),
    ("his face", "your face"),
    ("his voice", "your voice"),
    ("his tone", "your tone"),
    ("his fluster", "your fluster"),
    ("his reaction", "your reaction"),
    ("his nervousness", "your nervousness"),
    ("his honesty", "your honesty"),
    ("his patience", "your patience"),
    ("his focus", "your focus"),
    ("his stiffness", "your stiffness"),
    ("his retreat", "your retreat"),
    ("his posture", "your posture"),
    ("his frozen posture", "your frozen posture"),
    ("his expression", "your expression"),
    ("his forehead", "your forehead"),
    ("his thoughts", "your thoughts"),
    ("his curiosity", "your curiosity"),
    ("his words", "your words"),
    ("his breath", "your breath"),
    ("his collar", "your collar"),
    ("his hands", "your hands"),
    ("his throat", "your throat"),
    ("his shoulder", "your shoulder"),
    ("his shoulders", "your shoulders"),
    ("his smile", "your smile"),
    ("his eye ", "your eye "),
    ("his eye,", "your eye,"),
    ("his eye.", "your eye."),
    ("his plate", "your plate"),
    
    # Interactions: prepositions + him
    ("to him", "to you"),
    ("at him", "at you"),
    ("with him", "with you"),
    ("for him", "for you"),
    ("about him", "about you"),
    ("from him", "from you"),
    ("on him", "on you"),
    ("near him", "near you"),
    ("around him", "around you"),
    ("past him", "past you"),
    ("toward him", "toward you"),
    ("towards him", "towards you"),
    
    # Verb + him
    ("gives him an easy out", "gives you an easy out"),
    ("gives him a look", "gives you a look"),
    ("gives him a", "gives you a"),
    ("gives him room", "gives you room"),
    ("giving him room", "giving you room"),
    ("giving him", "giving you"),
    ("looks him over", "looks you over"),
    ("catches him", "catches you"),
    ("watches him", "watches you"),
    ("notices him", "notices you"),
    ("tells him", "tells you"),
    ("asks him", "asks you"),
    ("reassures him", "reassures you"),
    ("helping him", "helping you"),
    ("rescue him", "rescue you"),
    ("inviting him", "inviting you"),
    ("stop him", "stop you"),
    ("pull him", "pull you"),
    ("press him", "press you"),
    ("derailing him", "derailing you"),
    ("lets him", "lets you"),
    ("see him", "see you"),
    ("seeing him", "seeing you"),
    ("hear him", "hear you"),
    ("hearing him", "hearing you"),
    ("points at him", "points at you"),
    ("smiles at him", "smiles at you"),
    ("glances at him", "glances at you"),
    ("looks at him", "looks at you"),
    ("looks back at him", "looks back at you"),
    ("turn to him", "turn to you"),
    ("turns to him", "turns to you"),
    ("comes back to him", "comes back to you"),
]

for o, n in replacements:
    text = text.replace(o, n)

with open(path, 'w', encoding='utf-8') as f:
    f.write(text)

print("Applied 2nd-person perspective transformation successfully.")
